name: deplay-hexo-blog
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 安装nodejs
      - name: install nodejs
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16.x"
      # 安装依赖
      - name: install packages
        run: npm install
      # 清空缓存
      - name: clear
        run: npm clean
      # 打包项目
      - name: build
        run: npm run build
      # 文件复制到服务器 
      - name: copy dist file with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WXW_HOST }}
          username: ${{ secrets.WXW_USERNAME }}
          password: ${{ secrets.WXW_PASSWORD }}
          port: 22
          source: "public/"
          target: ${{ secrets.WXW_TARGET }}